'use client';
import {useState} from 'react';
import {Plus,Pencil,Settings2} from 'lucide-react';
import type {State} from '@/lib/types';
import {Badge,Empty,Section,Modal,deptName,type Run} from './ui';
type Kind='department'|'service'|'counter'|'user'|'closure'|'settings';
type Editor={kind:Kind;record:Record<string,unknown>};
const names:Record<Kind,string>={department:'Departments',service:'Services',counter:'Counter assignments',user:'Users & staff',closure:'Date closures',settings:'Organization'};
const departmentDefaults={name:'',active:true,opens:'09:00',closes:'17:00',break_start:'13:00',break_end:'14:00',workdays:[1,2,3,4,5],capacity:3,daily_limit:100,user_daily_limit:3,token_limit:1,checkin_before:10,checkin_after:10,cancel_minutes:30,horizon_days:30,fairness_minutes:30,response_minutes:3,accept_paused:false};
export default function Management({state,run}:{state:State;run:Run}){
  const [tab,setTab]=useState<Kind>('service'),[editor,setEditor]=useState<Editor|null>(null);const admin=state.user.role==='ADMIN';
  const kinds:Kind[]=admin?['service','department','counter','user','closure','settings']:['service','department','counter','user','closure'];
  const users=admin?state.users:state.users.filter(u=>u.role==='STAFF');
  function open(kind:Kind,record:Record<string,unknown>={}){setEditor({kind,record});}
  return <><div className="tabs">{kinds.map(k=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}>{names[k]}</button>)}</div><Section title={names[tab]} subtitle="Changes apply to future operations; existing visits retain their history." action={tab==='settings'?null:tab==='department'&&!admin?null:<button onClick={()=>open(tab)}><Plus size={16}/>Add {tab==='user'?'account':tab==='closure'?'closure':tab}</button>}>
  {tab==='service'&&<div className="table-scroll"><table><thead><tr><th>Service</th><th>Department</th><th>Duration</th><th>Prefix</th><th>Status</th><th/></tr></thead><tbody>{state.services.map(s=><tr key={s.id}><td><strong>{s.name}</strong></td><td>{deptName(state,s.department_id)}</td><td>{s.duration} min</td><td className="mono">{s.prefix}</td><td><Badge value={s.active?'ACTIVE':'DISABLED'}/></td><td><button className="icon-button" aria-label={`Edit ${s.name}`} onClick={()=>open('service',{...s})}><Pencil size={16}/></button></td></tr>)}</tbody></table></div>}
  {tab==='department'&&<div className="catalog-grid">{state.departments.map(d=><div className="catalog-card" key={d.id}><div className="flex-between"><span className="service-symbol"><Settings2/></span><Badge value={d.active?'ACTIVE':'DISABLED'}/></div><h3>{d.name}</h3><p>{d.opens}–{d.closes} · break {d.break_start}–{d.break_end}</p><small>{d.capacity} simultaneous appointments · {d.daily_limit} daily</small><button className="button secondary" onClick={()=>open('department',{...d})}>Edit schedule & rules<Pencil size={14}/></button></div>)}</div>}
  {tab==='counter'&&<div className="table-scroll"><table><thead><tr><th>Counter</th><th>Department</th><th>Staff / shift</th><th>Services</th><th>Status</th><th/></tr></thead><tbody>{state.counters.map(c=><tr key={c.id}><td><strong>{c.name}</strong></td><td>{deptName(state,c.department_id)}</td><td>{state.users.find(u=>u.id===c.staff_id)?.name??'Unassigned'}<small>{c.shift_start}–{c.shift_end}</small></td><td>{c.service_ids.map(id=>state.services.find(s=>s.id===id)?.name).join(', ')}</td><td><Badge value={c.status}/></td><td><button className="icon-button" aria-label={`Edit ${c.name}`} onClick={()=>open('counter',{...c})}><Pencil size={16}/></button></td></tr>)}</tbody></table></div>}
  {tab==='user'&&<div className="table-scroll"><table><thead><tr><th>Account</th><th>Role</th><th>Department</th><th>Status</th><th/></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.name}</strong><small>{u.email}</small></td><td><Badge value={u.role}/></td><td>{u.department_id?deptName(state,u.department_id):'Organization'}</td><td><Badge value={u.active?'ACTIVE':'DISABLED'}/></td><td><button disabled={u.id===state.user.id} className="icon-button" aria-label={`Edit ${u.name}`} onClick={()=>open('user',{...u})}><Pencil size={16}/></button></td></tr>)}</tbody></table></div>}
  {tab==='closure'&&(state.closures.length?<div className="table-scroll"><table><thead><tr><th>Department</th><th>Date</th><th>Reason</th><th/></tr></thead><tbody>{state.closures.map(c=><tr key={c.id}><td>{deptName(state,c.department_id)}</td><td>{c.day}</td><td>{c.reason}</td><td><button className="text-button danger-text" onClick={()=>run('deleteClosure',{id:c.id}).catch(()=>{})}>Remove closure</button></td></tr>)}</tbody></table></div>:<Empty title="No upcoming date closures" detail="Add a holiday or one-off closure to prevent new bookings."/>)}
  {tab==='settings'&&<div className="organization-settings"><h3>{state.settings.name}</h3><p>Timezone: {state.settings.timezone}</p><button className="button secondary" onClick={()=>open('settings',{...state.settings})}>Edit organization</button></div>}
  </Section>{editor&&<EditorForm editor={editor} state={state} run={run} close={()=>setEditor(null)}/>}</>;
}
function EditorForm({editor,state,run,close}:{editor:Editor;state:State;run:Run;close:()=>void}){
  const {kind,record}=editor;const r:Record<string,unknown>={...(kind==='department'?departmentDefaults:{}),...record};const admin=state.user.role==='ADMIN';const [error,setError]=useState('');
  const [dept,setDept]=useState(String(r.department_id??state.user.department_id??state.departments[0]?.id??''));const [role,setRole]=useState(String(r.role??'STAFF'));
  function field(label:string,key:string,type='text',defaultValue:unknown=r[key]??'',required=true,min?:number,max?:number){return <label key={key}>{label}<input name={key} type={type} defaultValue={String(defaultValue)} required={required} min={min} max={max} minLength={key==='password'?12:undefined} maxLength={key==='password'?128:type==='text'?100:undefined}/></label>;}
  const departmentSelect=<label>Department<select aria-label="Department" name="department_id" value={dept} disabled={!!r.id&&kind!=='user'} onChange={e=>setDept(e.target.value)}>{kind==='user'&&<option value="">Organization / none</option>}{state.departments.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select></label>;
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');const f=new FormData(e.currentTarget);const p:Record<string,unknown>={...r};
    if(kind==='department'){for(const key of Object.keys(departmentDefaults)){if(['active','accept_paused'].includes(key))p[key]=f.has(key);else if(key==='workdays')p[key]=f.getAll(key).map(Number);else p[key]=typeof departmentDefaults[key as keyof typeof departmentDefaults]==='number'?Number(f.get(key)):String(f.get(key));}}
    if(kind==='service'){Object.assign(p,{department_id:dept,name:f.get('name'),duration:Number(f.get('duration')),prefix:f.get('prefix'),active:f.has('active')});}
    if(kind==='counter'){Object.assign(p,{department_id:dept,name:f.get('name'),staff_id:f.get('staff_id')||null,service_ids:f.getAll('service_ids'),shift_start:f.get('shift_start'),shift_end:f.get('shift_end')});}
    if(kind==='user'){Object.assign(p,{name:f.get('name'),email:f.get('email'),phone:f.get('phone')??'',role,department_id:dept||null,active:f.has('active')});if(f.get('password'))p.password=f.get('password');}
    if(kind==='closure')Object.assign(p,{department_id:dept,day:f.get('day'),reason:f.get('reason')});
    if(kind==='settings')Object.assign(p,{name:f.get('name'),timezone:f.get('timezone')});
    try{await run(kind,p);close();}catch(e){setError(e instanceof Error?e.message:'Save failed.');}
  }
  return <Modal title={`${r.id?'Edit':'Configure'} ${kind==='user'?'account':kind}`} onClose={close}><form onSubmit={submit}><div className="form-grid">
  {kind==='department'&&<>{field('Department name','name')}{field('Opening time','opens','time')}{field('Closing time','closes','time')}{field('Break starts','break_start','time')}{field('Break ends','break_end','time')}{field('Simultaneous appointment capacity','capacity','number',r.capacity,true,1,100)}{field('Appointments per department/day','daily_limit','number',r.daily_limit,true,1,10000)}{field('Appointments per customer/day','user_daily_limit','number',r.user_daily_limit,true,1,50)}{field('Active tokens per customer','token_limit','number',r.token_limit,true,1,10)}{field('Check-in minutes before','checkin_before','number',r.checkin_before,true,0,120)}{field('Check-in minutes after','checkin_after','number',r.checkin_after,true,0,120)}{field('Cancellation cutoff (minutes)','cancel_minutes','number',r.cancel_minutes,true,0,1440)}{field('Booking horizon (days)','horizon_days','number',r.horizon_days,true,1,365)}{field('Walk-in fairness threshold (minutes)','fairness_minutes','number',r.fairness_minutes,true,1,240)}{field('No-response window (minutes)','response_minutes','number',r.response_minutes,true,1,60)}<div className="full-width"><span className="field-title">Working days</span><div className="checkbox-grid">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((d,i)=><label className="checkbox-label" key={d}><input type="checkbox" name="workdays" value={i+1} defaultChecked={(r.workdays as number[])?.includes(i+1)}/>{d}</label>)}</div></div><label className="checkbox-label"><input type="checkbox" name="active" defaultChecked={!!r.active}/>Department active</label><label className="checkbox-label"><input type="checkbox" name="accept_paused" defaultChecked={!!r.accept_paused}/>Allow walk-ins when counters paused</label></>}
  {kind==='service'&&<>{departmentSelect}{field('Service name','name')}{field('Service duration (minutes)','duration','number',r.duration??10,true,5,240)}{field('Token prefix (1–4 uppercase letters)','prefix','text',r.prefix??'DV')}<label className="checkbox-label"><input name="active" type="checkbox" defaultChecked={r.active!==false}/>Service active</label></>}
  {kind==='counter'&&<>{departmentSelect}{field('Counter name','name')}<label>Assigned staff<select aria-label="Assigned staff" name="staff_id" defaultValue={String(r.staff_id??'')}><option value="">Unassigned</option>{state.users.filter(u=>u.role==='STAFF'&&u.department_id===dept&&u.active).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label>{field('Shift starts','shift_start','time',r.shift_start??'09:00')}{field('Shift ends','shift_end','time',r.shift_end??'17:00')}<div className="full-width"><span className="field-title">Supported services</span><div className="checkbox-grid">{state.services.filter(s=>s.department_id===dept).map(s=><label className="checkbox-label" key={s.id}><input type="checkbox" name="service_ids" value={s.id} defaultChecked={(r.service_ids as string[]|undefined)?.includes(s.id)}/>{s.name}</label>)}</div></div></>}
  {kind==='user'&&<>{field('Full name','name')}{field('Email address','email','email')}{field('Phone','phone','tel',r.phone??'',false)}<label>Role<select aria-label="Role" value={role} onChange={e=>setRole(e.target.value)}>{(admin?['CUSTOMER','STAFF','MANAGER','ADMIN']:['STAFF']).map(role=><option key={role}>{role}</option>)}</select></label>{departmentSelect}{field(r.id?'New password (leave blank to keep current)':'Password (at least 12 characters)','password','password','',!r.id)}<label className="checkbox-label"><input type="checkbox" name="active" defaultChecked={r.active!==false}/>Account active</label></>}
  {kind==='closure'&&<>{departmentSelect}{field('Closure date','day','date')}{field('Reason','reason')}</>}
  {kind==='settings'&&<>{field('Organization name','name')}{field('IANA timezone','timezone','text',r.timezone??'Asia/Karachi')}</>}
  </div>{kind==='closure'&&<p className="report-note">A closure blocks new bookings; review existing appointments and use delay/reschedule to notify affected visitors.</p>}{error&&<div className="alert" role="alert">{error}</div>}<div className="modal-actions"><button className="button secondary" type="button" onClick={close}>Cancel</button><button type="submit">Save changes</button></div></form></Modal>;
}


