'use client';
import {useState} from 'react';
import {Clock3,Play,Check,SkipForward,RotateCcw,PhoneCall,Users,Search} from 'lucide-react';
import type {State,Counter} from '@/lib/types';
import {Badge,Empty,Section,Stat,time,deptName,type Run} from './ui';
export function StaffQueue({state,run}:{state:State;run:Run}){
  const [filter,setFilter]=useState('ACTIVE'),[search,setSearch]=useState('');const counters=state.user.role==='STAFF'?state.counters.filter(c=>c.staff_id===state.user.id):state.counters;
  const tokens=state.tokens.filter(t=>(filter==='ALL'||filter==='ACTIVE'&&['WAITING','CALLED','IN_SERVICE','SKIPPED'].includes(t.status)||t.status===filter)&&`${t.number} ${t.user_name} ${t.service_name}`.toLowerCase().includes(search.toLowerCase()));
  return <><div className="counter-grid">{counters.map(c=><CounterCard key={c.id} state={state} counter={c} run={run}/>)}</div><Section title="Service queue" subtitle="Appointment arrivals and walk-in visitors in one view." action={<span className="count-chip">{tokens.filter(t=>t.status==='WAITING').length} waiting</span>}><div className="table-tools"><label className="search-input"><Search size={17}/><input aria-label="Search queue" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search token, visitor or service"/></label><select aria-label="Queue status" value={filter} onChange={e=>setFilter(e.target.value)}>{['ACTIVE','ALL','WAITING','CALLED','IN_SERVICE','SKIPPED','COMPLETED','MISSED'].map(s=><option key={s}>{s}</option>)}</select></div>{tokens.length?<div className="table-scroll"><table><thead><tr><th>Token / visitor</th><th>Service</th><th>Type</th><th>Wait / position</th><th>Status</th><th>Actions</th></tr></thead><tbody>{tokens.map(t=><tr key={t.id}><td><strong className="mono">{t.number}</strong><small>{t.user_name}</small></td><td>{t.service_name}</td><td><span className="type-tag">{t.appointment_id?'Appointment':'Walk-in'}</span></td><td>{t.estimated_wait!=null?`${t.estimated_wait} min`:'—'}<small>{t.position?`Position ${t.position}`:time(t.created_at,state.settings.timezone,false)}</small></td><td><Badge value={t.status}/></td><td><div className="row-actions">{t.status==='CALLED'&&<><button className="button compact" onClick={()=>run('start',{tokenId:t.id}).catch(()=>{})}><Play size={13}/>Start</button><button className="button secondary compact" onClick={()=>run('skip',{tokenId:t.id}).catch(()=>{})}><SkipForward size={13}/>Skip</button></>}{t.status==='IN_SERVICE'&&<button className="button compact" onClick={()=>run('complete',{tokenId:t.id}).catch(()=>{})}><Check size={13}/>Complete</button>}{['CALLED','SKIPPED'].includes(t.status)&&<><button className="text-button" onClick={()=>run('recall',{tokenId:t.id}).catch(()=>{})}><RotateCcw size={13}/>Recall</button><button className="text-button danger-text" onClick={()=>run('miss',{tokenId:t.id}).catch(()=>{})}>Missed</button></>}</div></td></tr>)}</tbody></table></div>:<Empty title="The queue is clear" detail="New walk-ins and checked-in appointments will appear here."/>}</Section></>;
}
function CounterCard({state,counter:c,run}:{state:State;counter:Counter;run:Run}){
  const current=state.tokens.find(t=>t.counter_id===c.id&&['CALLED','IN_SERVICE'].includes(t.status));const allowed=state.user.role!=='STAFF'||c.staff_id===state.user.id;
  return <div className="counter-card"><div className="counter-card-head"><span className="service-symbol"><Users size={19}/></span><Badge value={c.status}/></div><h3>{c.name}</h3><p>{deptName(state,c.department_id)}</p><small>{state.users.find(u=>u.id===c.staff_id)?.name??(c.staff_id===state.user.id?state.user.name:c.staff_id?'Staff assigned':'No staff assigned')} · {c.shift_start}–{c.shift_end}</small><div className="counter-current"><span>{current?'NOW SERVING':'READY FOR SERVICE'}</span><strong>{current?.number??'—'}</strong>{current&&<small>{current.user_name}</small>}</div>{allowed&&<div className="counter-actions"><button disabled={c.status!=='AVAILABLE'||!c.staff_id} onClick={()=>run('call',{counterId:c.id}).catch(()=>{})}><PhoneCall size={15}/>Call next</button>{c.status!=='BUSY'&&<select aria-label={`Status for ${c.name}`} value={c.status} onChange={e=>run('counterStatus',{counterId:c.id,status:e.target.value}).catch(()=>{})}><option value="AVAILABLE">Available</option><option value="BREAK">Break</option><option value="CLOSED">Closed</option></select>}</div>}</div>;
}
export function Counters({state,run}:{state:State;run:Run}){return <><div className="stats-grid"><Stat label="Total counters" value={state.counters.length}/><Stat label="Available" value={state.counters.filter(c=>c.status==='AVAILABLE').length}/><Stat label="In service" value={state.counters.filter(c=>c.status==='BUSY').length}/><Stat label="Paused / closed" value={state.counters.filter(c=>['BREAK','CLOSED'].includes(c.status)).length}/></div><div className="counter-grid">{state.counters.map(c=><CounterCard key={c.id} state={state} counter={c} run={run}/>)}</div></>;}
function Bars({values}:{values:{label:string;value:number;secondary?:string}[]}){const max=Math.max(1,...values.map(v=>v.value));return <div className="horizontal-bars">{values.map((v,i)=><div key={`${v.label}-${i}`}><div className="bar-label"><span>{v.label}</span><strong>{v.value}{v.secondary??''}</strong></div><div className="bar-track"><div style={{width:`${v.value/max*100}%`}}/></div></div>)}</div>;}
export function Reports({state}:{state:State}){const a=state.analytics;if(!a)return <Empty title="Reports unavailable"/>;const max=Math.max(1,...a.hourly.map(h=>h.visitors));return <><div className="stats-grid"><Stat label="Appointments" value={a.appointments} detail="Scheduled on the report date"/><Stat label="Walk-in visitors" value={a.walkins} detail="Tokens issued on report date"/><Stat label="Completed services" value={a.completed} detail="Arrivals on report date"/><Stat label="Average waiting time" value={`${a.averageWait} min`} detail="Measured queue-to-service time"/></div><div className="stats-grid small-stats"><Stat label="Average service" value={`${a.averageService} min`}/><Stat label="Missed appointments" value={a.missed}/><Stat label="Cancellation rate" value={`${a.cancellationRate}%`}/><Stat label="No-show rate" value={`${a.noShowRate}%`}/></div><Section title="Visitor arrivals by hour" subtitle={`Use the peaks to plan service coverage. Times in ${state.settings.timezone}.`}><div className="column-chart" role="img" aria-label="Hourly visitor arrivals">{a.hourly.map(h=><div className="chart-column" key={h.hour} title={`${h.hour}: ${h.visitors} visitors`}><span>{h.visitors||''}</span><div style={{height:`${Math.max(2,h.visitors/max*140)}px`}}/><small>{h.hour.slice(0,2)}</small></div>)}</div></Section><div className="two-col"><Section title="Department demand" subtitle="Visitors and measured average wait."><Bars values={a.departments.map(d=>({label:`${d.name} · ${d.wait} min wait`,value:d.visitors}))}/></Section><Section title="Popular services" subtitle="Most visited services for the report date."><Bars values={a.services.map(s=>({label:s.name,value:s.visitors}))}/></Section><Section title="Staff workload" subtitle="Completed visits attributed to the serving staff."><Bars values={a.staff.map(s=>({label:s.name,value:s.completed}))}/><p className="report-note">Serving staff identity is recorded when a token is called.</p></Section><Section title="Seven-day visitor trend" subtitle="Daily token arrivals, ending on the report date."><Bars values={a.trends.map(t=>({label:t.day,value:t.visitors}))}/></Section></div><Section title="Hourly queue snapshot" subtitle="Approximate waiting population at each half-hour; terminal cancellations/no-shows are excluded."><Bars values={a.hourly.filter(h=>Number(h.hour.slice(0,2))>=7&&Number(h.hour.slice(0,2))<=19).map(h=>({label:h.hour,value:h.queue}))}/></Section><div className="tip"><Clock3 size={21}/><div><strong>Understand the numbers</strong><p>Waiting time starts at the later of queue entry or appointment eligibility and ends at service start. Rates divide the selected day’s missed/cancelled appointments by all scheduled appointments. Active counters and waiting totals represent the current queue.</p></div></div></>;}
export function Audit({state}:{state:State}){return <Section title="Activity log" subtitle="The latest 100 authorized staff, configuration, and service events.">{state.events.length?<div className="table-scroll"><table><thead><tr><th>Activity</th><th>Actor</th><th>Time</th><th>Details</th></tr></thead><tbody>{state.events.map(e=><tr key={e.id}><td><strong>{e.kind.replaceAll('.',' / ').replaceAll('_',' ')}</strong></td><td>{e.actor_name}</td><td>{time(e.created_at,state.settings.timezone)}</td><td><span className="audit-details">{Object.keys(e.details).length?JSON.stringify(e.details):'—'}</span></td></tr>)}</tbody></table></div>:<Empty title="No activity recorded yet"/>}</Section>;}

